export const data = {
    klassrum: [
      {
        name: "H221",
        grid: [
          [
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: "item-1728395558391", person: 1 },
            { id: "item-1728395558639", person: 1 },
          ],
          [
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: "item-1728395560144", person: 1 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
          ],
          [
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: "item-1728395557488", person: 1 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
          ],
          [
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
          ],
          [
            { id: "item-1728395563304", person: 1 },
            { id: "item-1728395562912", person: 1 },
            { id: "item-1728395557831", person: 1 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: "item-1728395562504", person: 1 },
            { id: "item-1728395559832", person: 1 },
          ],
          [
            { id: null, person: 0 },
            { id: "item-1728395561288", person: 1 },
            { id: "item-1728395560888", person: 1 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
            { id: null, person: 0 },
          ],
        ],
        cols: 7,
        rows: 6,
      },
    ],
    klasser: [
      {
        namn: "peters klass",
        personer: [
          "",
          "Alexander",
          "Alexander",
          "Rasmus",
          "Sammy",
          "Roham",
          "Oscar",
          "Alicia",
          "Tore",
          "Isac",
          "Hugo",
          "Maja",
          "Alice",
          "Prodromos",
          "Gabriel",
          "Ali k",
          "Katerina",
          "Oscar B",
          "Isabella",
          "Tassen",
          "Tilde",
          "Elisabeth",
          "Jamie",
          "Nike",
          "Elsa",
          "Anna",
          "Iman",
          "Anna",
          "Emil",
          "Alexia",
          "Alva",
          "Astrid",
          "Markus",
          "Sid",
          "Hampus",
          "Hannes",
          "William",
          "Bosse",
          "Lylly",
          "Joel",
          "Otto",
          "Erika",
          "Vincent",
          "Ali G",
          "Mona",
          "Walter",
          "Ellin",
          "Ellen",
          "Maria",
          "Klara",
          "Thea",
          "Philip",
          "Turid",
          "Sueda",
          "Sador",
          "Hedvig",
          "Ines",
          "Hampus",
          "Linnèa",
          "Danielle",
          "Vera",
          "William",
          "Sofia",
          "Emilia",
          "Emilia",
          "Erik",
          "Astrid",
          "Filicia",
          "Hussein",
          "Eli",
          "Signe",
          "Annie",
          "Jakob",
          "Moa",
          "Andrea",
          "Inès",
          "Emil",
          "Farhiya",
          "Wilma",
          "Stella",
          "Isak",
          "Arvid",
          "Viggo",
          "Linus",
          "Oliver",
          "Samuel",
          "Jakob",
          "Eliot",
          "Eric",
          "Artur",
          "Noah",
          "Isak",
          "Malcolm",
          "Tony",
          "Aria",
          "Noah",
          "Livia",
          "Sixsten",
          "Alex",
          "Matilda",
          "Ryan",
          "Uktam",
          "Olle",
          "Altan",
          "Juni",
          "Maja",
          "Rebecca",
          "Stina",
          "Kevin",
          "Melike",
          "Elin",
          "Elsa",
          "Gabriel",
          "Lo",
          "Enisa",
          "Myra",
          "Alsu",
          "Ida",
          "Madeleine",
          "Kiara",
          "Astrid",
          "Oscar W",
          "Stella",
          "Tindra",
          "Julia",
          "Alvina",
          "Sofia",
          "Ceasar",
        ],
      },
      {
        namn: "7G",
        personer: [
          "",
          "henry",
          "Kalle",
          "Fredrik",
          "carl",
          "Johan",
          "Artur",
          "Mattias",
        ],
      },
    ],
  };
